// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: sms_message.proto

package sms_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	CreatedAt   string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	Text        string `protobuf:"bytes,3,opt,name=text,proto3" json:"text"`
	Recipient   string `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient"`
	ExpiresAt   string `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at"`
	Otp         string `protobuf:"bytes,6,opt,name=otp,proto3" json:"otp"`
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number"`
	SendCount   int64  `protobuf:"varint,8,opt,name=send_count,json=sendCount,proto3" json:"send_count"`
}

func (x *Sms) Reset() {
	*x = Sms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms) ProtoMessage() {}

func (x *Sms) ProtoReflect() protoreflect.Message {
	mi := &file_sms_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms.ProtoReflect.Descriptor instead.
func (*Sms) Descriptor() ([]byte, []int) {
	return file_sms_message_proto_rawDescGZIP(), []int{0}
}

func (x *Sms) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sms) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Sms) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Sms) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Sms) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Sms) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *Sms) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Sms) GetSendCount() int64 {
	if x != nil {
		return x.SendCount
	}
	return 0
}

type GenerateOtp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber  string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number"`
	ExpiresAt    string `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at"`
	Otp          string `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp"`
	SmsId        string `protobuf:"bytes,4,opt,name=sms_id,json=smsId,proto3" json:"sms_id"`
	ReceiverType string `protobuf:"bytes,5,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type"`
}

func (x *GenerateOtp) Reset() {
	*x = GenerateOtp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateOtp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOtp) ProtoMessage() {}

func (x *GenerateOtp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOtp.ProtoReflect.Descriptor instead.
func (*GenerateOtp) Descriptor() ([]byte, []int) {
	return file_sms_message_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateOtp) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GenerateOtp) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *GenerateOtp) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *GenerateOtp) GetSmsId() string {
	if x != nil {
		return x.SmsId
	}
	return ""
}

func (x *GenerateOtp) GetReceiverType() string {
	if x != nil {
		return x.ReceiverType
	}
	return ""
}

type ConfirmOtpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmsId string `protobuf:"bytes,1,opt,name=sms_id,json=smsId,proto3" json:"sms_id"`
	Otp   string `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp"`
}

func (x *ConfirmOtpRequest) Reset() {
	*x = ConfirmOtpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOtpRequest) ProtoMessage() {}

func (x *ConfirmOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOtpRequest.ProtoReflect.Descriptor instead.
func (*ConfirmOtpRequest) Descriptor() ([]byte, []int) {
	return file_sms_message_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmOtpRequest) GetSmsId() string {
	if x != nil {
		return x.SmsId
	}
	return ""
}

func (x *ConfirmOtpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type GetSmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmsId string `protobuf:"bytes,1,opt,name=sms_id,json=smsId,proto3" json:"sms_id"`
}

func (x *GetSmsRequest) Reset() {
	*x = GetSmsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSmsRequest) ProtoMessage() {}

func (x *GetSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSmsRequest.ProtoReflect.Descriptor instead.
func (*GetSmsRequest) Descriptor() ([]byte, []int) {
	return file_sms_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetSmsRequest) GetSmsId() string {
	if x != nil {
		return x.SmsId
	}
	return ""
}

var File_sms_message_proto protoreflect.FileDescriptor

var file_sms_message_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x6d, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x01,
	0x0a, 0x03, 0x53, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x73, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x74, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f,
	0x74, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x6d, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x6d, 0x73, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3c, 0x0a, 0x11, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x6d, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x6d, 0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x22, 0x26, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6d, 0x73, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6d, 0x73, 0x49, 0x64, 0x42,
	0x16, 0x5a, 0x14, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6d, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sms_message_proto_rawDescOnce sync.Once
	file_sms_message_proto_rawDescData = file_sms_message_proto_rawDesc
)

func file_sms_message_proto_rawDescGZIP() []byte {
	file_sms_message_proto_rawDescOnce.Do(func() {
		file_sms_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_sms_message_proto_rawDescData)
	})
	return file_sms_message_proto_rawDescData
}

var file_sms_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sms_message_proto_goTypes = []interface{}{
	(*Sms)(nil),               // 0: genproto.Sms
	(*GenerateOtp)(nil),       // 1: genproto.GenerateOtp
	(*ConfirmOtpRequest)(nil), // 2: genproto.ConfirmOtpRequest
	(*GetSmsRequest)(nil),     // 3: genproto.GetSmsRequest
}
var file_sms_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sms_message_proto_init() }
func file_sms_message_proto_init() {
	if File_sms_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sms_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateOtp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmOtpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSmsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sms_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sms_message_proto_goTypes,
		DependencyIndexes: file_sms_message_proto_depIdxs,
		MessageInfos:      file_sms_message_proto_msgTypes,
	}.Build()
	File_sms_message_proto = out.File
	file_sms_message_proto_rawDesc = nil
	file_sms_message_proto_goTypes = nil
	file_sms_message_proto_depIdxs = nil
}
